/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicolasg-chausseau' at '07/02/18 4:08 PM' with Gradle 3.0
 *
 * @author nicolasg-chausseau, @date 07/02/18 4:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
